### ISSUE TITLE
Very slow analysis when more than 1,000 samples collected.

### ISSUE THREAD

**Issue by LeifAndersen** [stamourv/feature-profile#18]
Maybe its just my imagination, but the analysis has been very slow lately on runs with over 1,000 collected samples.

I don't remember it originally taking this long, so I suspect something has bit-rotted (performance wise).

**Comment by LeifAndersen** [comment]
Hmm...running this program seems to indicate a linear correlation with program time and profiling time, which make sense. So my current thought is that if there is indeed a problem, its in the contract plugin:

```
#lang racket

(require feature-profile)

(define size (string->number (vector-ref (current-command-line-arguments) 0)))

(feature-profile
 (for ([i (in-range (* 1000000000 size))])
   (+ 1 1)))
```

**Comment by LeifAndersen** [comment]
And never mind, this program also disproves that idea:

```
#lang racket

(require feature-profile)

(define size (string->number (vector-ref (current-command-line-arguments) 0)))

(feature-profile
 (for ([i (in-range (* 100000 size))])
   (contract integer? i 'pos 'neg #f #f)))
```

I'm still getting very slow reports on contract heavy traces, but I'm going to close this issue until I can find something repeatable.

**Comment by LeifAndersen** [comment]
Okay, I am re-opening the issue as I've condensed the problem to a single program:

```
#lang racket

(module const racket
  (provide π)
  (define π 3.14))

(module utils typed/racket
  (provide find-area)
  (require/typed (submod ".." const)
                 [π Number])
  (: find-area (-> Number Number))
  (define (find-area radius)
    (* (expt radius 2)
       π)))

(module main racket
  (require (submod ".." utils))
  (require feature-profile)
  (feature-profile
   (for/list ([i (in-range 10000000)])
     (find-area i))))

(require 'main)
```

As the values goes from 10000000 to 20000000 to 40000000 you will notice the time more than doubling as well.  Once the number goes above 60000000, the analysis portion becomes unpractical to run.

**Comment by stamourv** [comment]
I've tracked it down to superlinear time in the regular profiler. Looking into it.

**Comment by LeifAndersen** [comment]
Cool. Kind of odd that it only affected that one program, but thanks.

**Comment by stamourv** [comment]
Found the cause, I think.
`for/list` is not tail-recursive, and so builds up stack space. Not a problem per se, but that makes some of the samples collected by the profiler (FS or otherwise) quite large (~50-100k frames).
I'm guessing that it doesn't get any larger because the stack periodically overflows into the heap, and the runtime's best-effort stack traces don't look extend to there.
The main loop of the profiler's analyzer is O(n-samples * sample-size), so large samples make it sad.

Not sure there's much we can do about that, short of pruning samples. We'd lose some precision, but probably not in a qualitatively different way than what the stack overflowing into the heap already does.

Now, as far as the FSP (contract profiler, really) is concerned, the edge profile computed by the regular profiler (whose computation is the bottleneck here) is only needed for the boundary view, which is not displayed by default anymore. So we can avoid the problem in the vast majority of cases by computing it lazily. I'll make that change.
